# Generated by Django 5.2.17 on 2026-10-10 19:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('demolition', 'Demolition'), ('debris_clearing', 'Debris clearing'), ('carrying', 'Carrying materials'), ('earthworks', 'Earthworks / digging'), ('site_cleaning', 'Site cleaning'), ('scaffolding', 'Scaffolding helper'), ('masonry', "Bricklayer's helper"), ('drywall', 'Drywall helper'), ('plastering', 'Plastering helper'), ('painting', 'Painting helper')], max_length=20, verbose_name='job type')),
                ('description', models.TextField(verbose_name='description')),
                ('original_language', models.CharField(choices=[('de', 'Deutsch'), ('en', 'English'), ('ru', 'Русский'), ('uk', 'Українська'), ('pl', 'Polski'), ('ro', 'Română'), ('tr', 'Türkçe')], max_length=2, verbose_name='original language')),
                ('address', models.CharField(max_length=200, verbose_name='address')),
                ('district', models.CharField(choices=[('altstadt_lehel', 'Altstadt-Lehel'), ('ludwigsvorstadt_isarvorstadt', 'Ludwigsvorstadt-Isarvorstadt'), ('maxvorstadt', 'Maxvorstadt'), ('schwabing_west', 'Schwabing-West'), ('au_haidhausen', 'Au-Haidhausen'), ('sendling', 'Sendling'), ('sendling_westpark', 'Sendling-Westpark'), ('schwanthalerhoehe', 'Schwanthalerhöhe'), ('neuhausen_nymphenburg', 'Neuhausen-Nymphenburg'), ('moosach', 'Moosach'), ('milbertshofen_am_hart', 'Milbertshofen-Am Hart'), ('schwabing_freimann', 'Schwabing-Freimann'), ('bogenhausen', 'Bogenhausen'), ('berg_am_laim', 'Berg am Laim'), ('trudering_riem', 'Trudering-Riem'), ('ramersdorf_perlach', 'Ramersdorf-Perlach'), ('obergiesing_fasangarten', 'Obergiesing-Fasangarten'), ('untergiesing_harlaching', 'Untergiesing-Harlaching'), ('thalkirchen_obersendling_forstenried_fuerstenried_solln', 'Thalkirchen-Obersendling-Forstenried-Fürstenried-Solln'), ('hadern', 'Hadern'), ('pasing_obermenzing', 'Pasing-Obermenzing'), ('aubing_lochhausen_langwied', 'Aubing-Lochhausen-Langwied'), ('allach_untermenzing', 'Allach-Untermenzing'), ('feldmoching_hasenbergl', 'Feldmoching-Hasenbergl'), ('laim', 'Laim'), ('outside_munich', 'Munich area (outside the city)')], max_length=60, verbose_name='district')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('date', models.DateField(verbose_name='date')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('hours', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='hours')),
                ('workers_needed', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='workers needed')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('13.90'))], verbose_name='hourly rate (€)')),
                ('status', models.CharField(choices=[('open', 'Open'), ('filled', 'Filled'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='open', max_length=10, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('employer', models.ForeignKey(limit_choices_to={'role': 'employer'}, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL, verbose_name='employer')),
            ],
            options={
                'verbose_name': 'job',
                'verbose_name_plural': 'jobs',
                'constraints': [models.CheckConstraint(condition=models.Q(('hours__gte', 1), ('hours__lte', 10)), name='job_hours_1_to_10'), models.CheckConstraint(condition=models.Q(('workers_needed__gte', 1), ('workers_needed__lte', 10)), name='job_workers_needed_1_to_10')],
            },
        ),
    ]
