# Generated by Django 5.2.17 on 2026-10-07 14:02

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_size', models.PositiveSmallIntegerField(default=1, help_text='1 = only you. 2-10 = your crew, including you.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='team size')),
                ('skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('demolition', 'Demolition'), ('debris_clearing', 'Debris clearing'), ('carrying', 'Carrying materials'), ('earthworks', 'Earthworks / digging'), ('site_cleaning', 'Site cleaning'), ('scaffolding', 'Scaffolding helper'), ('masonry', "Bricklayer's helper"), ('drywall', 'Drywall helper'), ('plastering', 'Plastering helper'), ('painting', 'Painting helper')], max_length=20), size=None, verbose_name='skills')),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('de', 'German'), ('en', 'English'), ('ru', 'Russian'), ('uk', 'Ukrainian'), ('pl', 'Polish'), ('ro', 'Romanian'), ('tr', 'Turkish'), ('bg', 'Bulgarian'), ('hr', 'Croatian'), ('sr', 'Serbian'), ('bs', 'Bosnian'), ('hu', 'Hungarian'), ('sq', 'Albanian'), ('ar', 'Arabic'), ('it', 'Italian')], max_length=2), size=None, verbose_name='spoken languages')),
                ('legal_status', models.CharField(choices=[('gewerbe', 'Self-employed (Gewerbe)'), ('minijob', 'Minijob'), ('employed', 'Employed')], max_length=10, verbose_name='legal status')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'worker profile',
                'verbose_name_plural': 'worker profiles',
                'constraints': [models.CheckConstraint(condition=models.Q(('team_size__gte', 1), ('team_size__lte', 10)), name='worker_team_size_1_to_10')],
            },
        ),
    ]
