# Generated by Django 5.2.17 on 2026-10-07 16:02

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_worker_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, help_text='Leave empty if you hire as a private person.', max_length=150, verbose_name='company name')),
                ('trades', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('window_fitting', 'Window fitting'), ('drywall', 'Drywall'), ('plastering', 'Plastering'), ('painting', 'Painting'), ('tiling', 'Tiling'), ('roofing', 'Roofing'), ('bricklaying', 'Bricklaying'), ('carpentry', 'Carpentry'), ('electrical', 'Electrical'), ('plumbing_heating', 'Plumbing & heating'), ('landscaping', 'Landscaping'), ('demolition', 'Demolition'), ('general_contractor', 'General contractor'), ('private_person', 'Private person / own renovation'), ('other', 'Other')], max_length=20), size=None, verbose_name='trades')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'employer profile',
                'verbose_name_plural': 'employer profiles',
            },
        ),
    ]
