# Generated by Django 5.2.17 on 2026-10-08 07:07
# Operations written by hand: the yes/no field becomes a date (#13, spec D2 and D7).

from django.db import migrations, models
from django.utils import timezone


def boolean_to_date(apps, schema_editor):
    """Users who had the box ticked get the migration time, so nobody loses a confirmation."""
    # The historical model: the User as it is at this point of the migrations, not today's.
    User = apps.get_model('accounts', 'User')
    User.objects.filter(work_permit_confirmed=True).update(
        work_permit_confirmed_at=timezone.now()
    )


def date_to_boolean(apps, schema_editor):
    """Going back: every user with a date gets the box ticked again."""
    User = apps.get_model('accounts', 'User')
    User.objects.filter(work_permit_confirmed_at__isnull=False).update(
        work_permit_confirmed=True
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_employer_profile'),
    ]

    operations = [
        # 1. Add the new field next to the old one.
        migrations.AddField(
            model_name='user',
            name='work_permit_confirmed_at',
            field=models.DateTimeField(
                blank=True, null=True, verbose_name='work permit confirmed at'
            ),
        ),
        # 2. Copy the data while both fields exist.
        migrations.RunPython(boolean_to_date, date_to_boolean),
        # 3. Remove the old field.
        migrations.RemoveField(
            model_name='user',
            name='work_permit_confirmed',
        ),
    ]
