# Generated by Django 5.2.17 on 2026-10-08 13:36

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_work_permit_confirmed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='For example +49 151 12345678 or 0151 12345678.', max_length=30, validators=[accounts.validators.validate_phone], verbose_name='phone'),
        ),
    ]
